[workspace]
members = ["crates/rv-core", "crates/rv-session", "crates/rv-app"]
resolver = "2"
default-members = ["crates/rv-app"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"
rust-version = "1.90"
authors = ["Max Lv"]

[workspace.dependencies]
anyhow = "1"
directories = "6"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
keyring = { version = "3", features = ["apple-native", "sync-secret-service"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["net", "rt-multi-thread", "macros", "time", "sync", "io-util"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "serde"] }
vnc = { package = "vnc-rs", version = "0.5.3" }
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "ring"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
webpki-roots = "0.26"
openssl = { version = "0.10", features = ["vendored"] }
tokio-openssl = "0.6"
smallvec = "1"

rv-core = { path = "crates/rv-core" }
rv-session = { path = "crates/rv-session" }

[workspace.lints.clippy]
dbg_macro = "deny"
